In [12]:
import init
import numpy as np

In [2]:
from dataset.graph_loader import GraphLoader

In [4]:
data_path = '/Users/marvzhang/projects/tikazyq/auto-html/data/quotes.toscrape.com/json/http___quotes_toscrape_com_.json'
loader = GraphLoader(data_path)
loader.run()

Graph(num_nodes=145, num_edges=145,
      ndata_schemes={'feat': Scheme(shape=(106,), dtype=torch.float32)}
      edata_schemes={})


/Users/marvzhang/projects/tikazyq/auto-html/venv/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [7]:
features_counts = loader.nodes_features_tensor.detach().numpy().sum(axis=0)
features_counts

array([ 1., 10.,  2.,  2.,  2.,  1.,  1.,  1., 10.,  1.,  1., 10.,  2.,
        1., 40., 10., 10.,  1., 10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  3.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  2.,  1.,  3.,  1.,  2.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1., 10., 10., 10., 10., 10.,  1.,  1.,  1.,  1.,  2.,  1.,  1.,
        2.,  1., 55.,  1., 28.,  1.,  1.,  1.,  1., 10.,  1.,  3., 10.,
       32.,  1.], dtype=float32)

In [58]:
unique_features_idx = np.argwhere(features_counts == 1).T[0]
unique_features_idx

array([  0,   5,   6,   7,   9,  10,  13,  17,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30,  32,  33,  34,  35,  36,  37,
        38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,
        51,  52,  53,  54,  55,  57,  59,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  84,
        85,  86,  87,  89,  90,  92,  94,  96,  97,  98,  99, 101, 105])

In [60]:
np.array(loader.nodes_features)[unique_features_idx]

array([{'tag=body': 1},
       {'tag=a': 1, 'href=/': 1, 'style=text-decoration: none': 1},
       {'tag=div': 1, 'class=col-md-4': 1}, {'tag=p': 1},
       {'tag=div': 1, 'class=row': 1},
       {'tag=div': 1, 'class=col-md-8': 1}, {'tag=span': 1},
       {'tag=meta': 1, 'class=keywords': 1, 'itemprop=keywords': 1, 'content=change,deep-thoughts,thinking,world': 1},
       {'tag=a': 1, 'class=tag': 1, 'href=/tag/deep-thoughts/page/1/': 1},
       {'tag=a': 1, 'class=tag': 1, 'href=/tag/thinking/page/1/': 1},
       {'tag=a': 1, 'class=tag': 1, 'href=/tag/world/page/1/': 1},
       {'tag=div': 1, 'class=quote': 1, 'itemscope=': 1, 'itemtype=http://schema.org/CreativeWork': 1},
       {'tag=span': 1, 'class=text': 1, 'itemprop=text': 1},
       {'tag=span': 1},
       {'tag=small': 1, 'class=author': 1, 'itemprop=author': 1},
       {'tag=a': 1, 'href=/author/J-K-Rowling': 1},
       {'tag=div': 1, 'class=tags': 1},
       {'tag=meta': 1, 'class=keywords': 1, 'itemprop=keywords': 1, 'con

In [43]:
available_feature_names = [f for f in loader.nodes_features_enc.feature_names_ if f.split('=')[0] in ['class', 'tag', 'id']]
available_feature_names

['class=author',
 'class=col-md-4',
 'class=col-md-8',
 'class=container',
 'class=copyright',
 'class=footer',
 'class=header-box',
 'class=keywords',
 'class=next',
 'class=pager',
 'class=quote',
 'class=row',
 'class=sh-red',
 'class=tag',
 'class=tag-item',
 'class=tags',
 'class=tags-box',
 'class=text',
 'class=text-muted',
 'tag=a',
 'tag=body',
 'tag=div',
 'tag=footer',
 'tag=h1',
 'tag=h2',
 'tag=li',
 'tag=meta',
 'tag=nav',
 'tag=p',
 'tag=small',
 'tag=span',
 'tag=ul']

In [51]:
available_features_idx = np.argwhere(np.isin(loader.nodes_features_enc.feature_names_, np.array(available_feature_names))).T
available_features_idx

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  93,  94,  95,  96,  97,  98,  99,
        100, 101, 102, 103, 104, 105]])

In [52]:
np.array(loader.nodes_features_enc.feature_names_)[available_features_idx]

array([['class=author', 'class=col-md-4', 'class=col-md-8',
        'class=container', 'class=copyright', 'class=footer',
        'class=header-box', 'class=keywords', 'class=next',
        'class=pager', 'class=quote', 'class=row', 'class=sh-red',
        'class=tag', 'class=tag-item', 'class=tags', 'class=tags-box',
        'class=text', 'class=text-muted', 'tag=a', 'tag=body', 'tag=div',
        'tag=footer', 'tag=h1', 'tag=h2', 'tag=li', 'tag=meta',
        'tag=nav', 'tag=p', 'tag=small', 'tag=span', 'tag=ul']],
      dtype='<U49')

In [62]:
unique_available_features_idx = np.intersect1d(unique_features_idx, available_features_idx)
unique_available_features_idx

array([  5,   6,   7,   9,  10,  13,  17,  19,  94,  96,  97,  98,  99,
       101, 105])

In [61]:
np.array(loader.nodes_features_enc.feature_names_)[unique_available_features_idx]

array(['class=copyright', 'class=footer', 'class=header-box',
       'class=next', 'class=pager', 'class=sh-red', 'class=tags-box',
       'class=text-muted', 'tag=body', 'tag=footer', 'tag=h1', 'tag=h2',
       'tag=li', 'tag=nav', 'tag=ul'], dtype='<U49')